### ISSUE TITLE
After docker-compose up, rasa and rasa action server is not working on localhost as mentioned in Readme file.

### ISSUE THREAD

**Issue by Anmol-Yadav** [mccm-innovations/UiPath_Orchestrator_Chatbot#1]
Error: Requested URL / not found

**Comment by aarcosg** [comment]
Closing this issue. Please check #2 solution.

**Comment by Anmol-Yadav** [comment]
I have added version to rasa. How to add it to rasa-action-server? and what version to add to make it working?
