### ISSUE TITLE
UiPath API not returning anything because rasa and rasa action server are not responding.

### ISSUE THREAD

**Issue by Anmol-Yadav** [mccm-innovations/UiPath_Orchestrator_Chatbot#2]
![image](https://user-images.githubusercontent.com/33924572/69491732-06921200-0ebf-11ea-8d5a-0ea02377c169.png)

**Comment by aarcosg** [comment]
Hi. It looks like incompatibility issues with latest rasa versions. I have set in docker-compose.yml the specific container versions used when we were developing this project since it is not under maintenance right now.

**Comment by Anmol-Yadav** [comment]
I have updated the rasa version, but the issue is still there.
