### ISSUE TITLE
The API is returning the data but it is not being displayed on webchat.

### ISSUE THREAD

**Issue by Anmol-Yadav** [mccm-innovations/UiPath_Orchestrator_Chatbot#3]
![image](https://user-images.githubusercontent.com/33924572/70019583-bb0ef080-15af-11ea-89ab-949d0ee095de.png)

The UiPath API is returning me the assets information. However on the webchat i am not getting anything.

![image](https://user-images.githubusercontent.com/33924572/70019618-e1349080-15af-11ea-9458-979c7aa01922.png)

**Comment by aarcosg** [comment]
Hi @Anmol-Yadav,

I am sorry if this project is not working in your enviroment. We have executed it right now in a brand new cloud virtual machine and it is working just fine. We cannot provide any further support.
