### ISSUE TITLE
I have added version to rasa. How to add it to rasa-action-server? and what version to add to make it working?

### ISSUE THREAD

**Issue by Anmol-Yadav** [mccm-innovations/UiPath_Orchestrator_Chatbot#4]
I have added version to rasa. How to add it to rasa-action-server? and what version to add to make it working?

_Originally posted by @Anmol-Yadav in https://github.com/mccm-innovations/UiPath_Orchestrator_Chatbot/issues/1#issuecomment-560988678_

**Comment by aarcosg** [comment]
See #3
